# Generated by Django 5.1.1 on 2024-10-07 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('origin', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('category', models.CharField(choices=[('utensils', 'Бытовая утварь'), ('clothing', 'Одежда'), ('weapons', 'Оружие'), ('art', 'Живопись')], max_length=255)),
                ('history', models.TextField()),
                ('condition', models.CharField(choices=[('good', 'Хорошее'), ('restoration_needed', 'Требует реставрации')], max_length=255)),
            ],
        ),
    ]
